# Generated by Django 4.2.1 on 2023-05-17 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_string', models.CharField(max_length=50)),
                ('age_int', models.IntegerField(verbose_name='Возраст')),
                ('email_string', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('float_number', models.FloatField(verbose_name='Число с плавающей точкой')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['-name_string', 'age_int'],
            },
        ),
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_models', to='testapp.modelname', verbose_name='Связанная модель')),
            ],
            options={
                'verbose_name': 'Вторая модель',
                'verbose_name_plural': 'Вторые модели',
                'ordering': ['-model_name'],
            },
        ),
    ]
