# Generated by Django 4.2.1 on 2023-05-17 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_secondmodel_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondmodel',
            name='four',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 5, 3, 57, 472724, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
