# Generated by Django 4.2.1 on 2023-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_secondmodel_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondmodel',
            name='eight',
            field=models.TextField(default='default text'),
        ),
        migrations.AddField(
            model_name='secondmodel',
            name='five',
            field=models.DateTimeField(default='2020-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='secondmodel',
            name='nine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secondmodel',
            name='seven',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='secondmodel',
            name='six',
            field=models.IntegerField(default=0),
        ),
    ]
